spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/menu_db
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update

  main:
    allow-bean-definition-overriding: true